# .travis.yml
# This file should be at the root of your project
# use http://www.yamllint.com/ to check yml validity
language: ruby
cache: bundler
before_install:
  - gem install bundler
script:
  - bundle exec jekyll algolia
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
    - 2.4
exclude: [vendor]
